version: "3.7"
services:
  backend:
    build: .
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/product-assortment-db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres

  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: product-assortment-db
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"

  flyway:
    image: flyway/flyway:latest
    command: ["-url=jdbc:postgresql://db:5432/product-assortment-db", "-user=postgres", "-password=postgres", "migrate"]
    depends_on:
      - db
    volumes:
      - ./sql:/flyway/sql
