Spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/product_assortment
    username: postgres
    password: postgres

---
Spring:
  flyway:
    enabled: true
    locations: classpath:db/migration

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics


